[package]
name = "raymarching"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "1.3.32"
image = "0.24.5"
rand = "0.8.5"
macroquad = "0.3.25"
rayon = "1.7.0"